/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c TulipAgentService -a include/TulipAgentServiceAdaptor.h:src/TulipAgentServiceAdaptor.cpp resources/org.labri.TulipAgentService.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "TulipAgentServiceAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class TulipAgentService
 */

TulipAgentService::TulipAgentService(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

TulipAgentService::~TulipAgentService()
{
    // destructor
}

qlonglong TulipAgentService::pid() const
{
    // get the value of property pid
    return qvariant_cast< qlonglong >(parent()->property("pid"));
}

void TulipAgentService::ShowAboutPage()
{
    // handle method call org.labri.Tulip.ShowAboutPage
    QMetaObject::invokeMethod(parent(), "ShowAboutPage");
}

void TulipAgentService::ShowPluginsCenter()
{
    // handle method call org.labri.Tulip.ShowPluginsCenter
    QMetaObject::invokeMethod(parent(), "ShowPluginsCenter");
}

void TulipAgentService::ShowWelcomeScreen()
{
    // handle method call org.labri.Tulip.ShowWelcomeScreen
    QMetaObject::invokeMethod(parent(), "ShowWelcomeScreen");
}

