CMAKE_MINIMUM_REQUIRED(VERSION 2.6)
PROJECT(%ProjectName:l%)

SET(PLUGIN_NAME %ProjectName:l%)
STRING(TOLOWER ${PLUGIN_NAME} PLUGIN_NAME)

FIND_PACKAGE(TULIP REQUIRED)
FIND_PACKAGE(Qt4  REQUIRED)
SET(QT_USE_QTOPENGL true)
INCLUDE(${QT_USE_FILE})

INCLUDE_DIRECTORIES(${TULIP_INCLUDE_DIR} ${QT_INCLUDE_DIR} ${CMAKE_CURRENT_BINARY_DIR} ${CMAKE_CURRENT_SOURCE_DIR})	

SET(LIB_SRCS
    %ProjectName:c%.cpp
    %ProjectName:c%ConfigWidget.cpp
)

SET(LIB_UI
    %ProjectName:c%ConfigWidget.ui
)

SET(LIB_MOC
    %ProjectName:c%.h
    %ProjectName:c%ConfigWidget.h
)

SET(LIB_RCC
)

QT4_WRAP_UI(LIB_UI_SRCS ${LIB_UI})
QT4_WRAP_CPP(LIB_MOC_SRCS ${LIB_MOC})
QT4_ADD_RESOURCES(LIB_RCC_SRCS ${LIB_RCC})

ADD_LIBRARY(${PLUGIN_NAME}-${TULIP_VERSION} SHARED ${LIB_SRCS} ${LIB_UI_SRCS} ${LIB_MOC_SRCS} ${LIB_RCC_SRCS})
TARGET_LINK_LIBRARIES(${PLUGIN_NAME}-${TULIP_VERSION} ${TULIP_LIBRARIES} ${QT_LIBRARIES})

INSTALL(TARGETS ${PLUGIN_NAME}-${TULIP_VERSION} DESTINATION ${TULIP_PLUGINS_DIR}/view)
