set(TULIP_INCLUDE_DIR ${TulipInclude} ${TulipBuildInclude} ${TulipOGLInclude} ${TulipOGLBuildInclude} ${TulipQtInclude} ${TulipQtBuildInclude})
set(TULIP_LIBRARY "${LibTulipName}")
set(TULIP_OGL_LIBRARY "${LibTulipOglName}")
set(TULIP_QT4_LIBRARY "${LibTulipQtName}")
set(TULIP_FOUND "YES")
set(TULIP_VERSION	"${TulipVersion}")
set(TULIP_PLUGIN_VERSION "${TulipVersion}")
set(TULIP_PLUGINS_PATH "${CMAKE_INSTALL_PREFIX}/${TulipLibInstallDir}tlp/")
