SET(TULIP_DIR ${CMAKE_INSTALL_PREFIX})
SET(TULIP_FOUND true)
SET(TULIP_INCLUDE_DIR ${TulipCoreBuildInclude} ${TulipCoreInclude} ${TulipOGLInclude} ${TulipGUIInclude} ${TulipPythonInclude})
SET(TULIP_LIBRARIES ${LibTulipCoreName} ${LibTulipOglName} ${LibTulipGUIName})

IF(WIN32)
  SET(TULIP_LIBRARIES_DIR ${TulipBinInstallDir})
ELSE(WIN32)
  SET(TULIP_LIBRARIES_DIR ${TulipLibInstallDir})
ENDIF(WIN32)
SET(TULIP_PLUGINS_DIR ${TulipPluginsInstallDir})
SET(TULIP_GLYPH_PLUGINS_DIR ${TulipGlyphPluginsInstallDir})
SET(TULIP_INTERACTOR_PLUGINS_DIR ${TulipInteractorPluginsInstallDir})
SET(TULIP_VIEW_PLUGINS_DIR ${TulipViewPluginsInstallDir})
SET(TULIP_PERSPECTIVE_PLUGINS_DIR ${TulipPerspectivePluginsInstallDir})
SET(TULIP_CORE_LIBRARY ${LibTulipCoreName})
SET(TULIP_OGL_LIBRARY ${LibTulipOglName})
SET(TULIP_GUI_LIBRARY ${LibTulipGUIName})
SET(TULIP_PYTHON_LIBRARY ${LibTulipPythonName})
SET(TULIP_VERSION ${Tulip_VERSION})
SET(TULIP_MM_VERSION ${TulipMMVersion})
SET(TULIP_SHARE_DIR ${TulipShareInstallDir})
SET(TULIP_USE_FILE ${CMAKE_SOURCE_DIR}/cmake/TulipUseFile.cmake)
