/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c TulipAgentService -a include/TulipAgentServiceAdaptor.h:src/TulipAgentServiceAdaptor.cpp resources/org.labri.TulipAgentService.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef TULIPAGENTSERVICEADAPTOR_H_1306835011
#define TULIPAGENTSERVICEADAPTOR_H_1306835011

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.labri.Tulip
 */
class TulipAgentService: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.labri.Tulip")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.labri.Tulip\">\n"
"    <property access=\"read\" type=\"x\" name=\"pid\"/>\n"
"    <method name=\"ShowWelcomeScreen\"/>\n"
"    <method name=\"ShowPluginsCenter\"/>\n"
"    <method name=\"ShowAboutPage\"/>\n"
"  </interface>\n"
        "")
public:
    TulipAgentService(QObject *parent);
    virtual ~TulipAgentService();

public: // PROPERTIES
    Q_PROPERTY(qlonglong pid READ pid)
    qlonglong pid() const;

public Q_SLOTS: // METHODS
    void ShowAboutPage();
    void ShowPluginsCenter();
    void ShowWelcomeScreen();
Q_SIGNALS: // SIGNALS
};

#endif
