SET(CHAR_SEP ":")
IF(WIN32)
SET(CHAR_SEP ";")
SET(ENV{PATH} "${BIN_DIR}/../../library/tulip-core/src;${BIN_DIR}/../../thirdparty/gzstream;$ENV{PATH}")
ENDIF(WIN32)
SET(ENV{PYTHONPATH} "${BIN_DIR}/../../library/tulip-python/tulip-core${CHAR_SEP}${SRC_DIR}/../../library/tulip-python/tulip-core${CHAR_SEP}${BIN_DIR}/../../library/tulip-python/stl${CHAR_SEP}$ENV{PYTHONPATH}")
IF(NOT SYSTEM_SIP)
SET(ENV{PYTHONPATH} "${BIN_DIR}/../../thirdparty/sip-4.13.2/siplib${CHAR_SEP}$ENV{PYTHONPATH}")
ENDIF()
EXECUTE_PROCESS(COMMAND ${SPHINX_EXECUTABLE} -b html -d ${BIN_DIR}/doctrees ${SOURCE_DIR} ${BIN_DIR}/html)
