SET(CHAR_SEP ":")
IF(WIN32)
SET(CHAR_SEP ";")
IF(MSVC)
SET(ENV{PATH} "${BIN_DIR}/../../library/tulip/src/Debug;${BIN_DIR}/../../library/tulip-ogl/src/Debug;${BIN_DIR}/../../library/tulip-qt/src/Debug;${BIN_DIR}/../../thirdparty/gzstream/Debug;${BIN_DIR}/../../thirdparty/ftgl/Debug;${QT_BIN_DIR};$ENV{PATH}")
ELSE(MSVC)
SET(ENV{PATH} "${BIN_DIR}/../../library/tulip/src;${BIN_DIR}/../../library/tulip-ogl/src;${BIN_DIR}/../../library/tulip-qt/src;${BIN_DIR}/../../thirdparty/gzstream;${BIN_DIR}/../../thirdparty/ftgl;${QT_BIN_DIR};$ENV{PATH}")
ENDIF(MSVC)
ENDIF(WIN32)
IF(MSVC)
SET(ENV{PYTHONPATH} "${BIN_DIR}/../../library/tulip-python/tulip/Debug${CHAR_SEP}${SRC_DIR}/../../library/tulip-python/tulip${CHAR_SEP}${BIN_DIR}/../../library/tulip-python/tulip-ogl/Debug${CHAR_SEP}${BIN_DIR}/../../library/tulip-python/tulipgui/Debug${CHAR_SEP}${BIN_DIR}/../../library/tulip-python/stl/Debug${CHAR_SEP}$ENV{PYTHONPATH}")
ELSE(MSVC)
SET(ENV{PYTHONPATH} "${BIN_DIR}/../../library/tulip-python/tulip${CHAR_SEP}${SRC_DIR}/../../library/tulip-python/tulip${CHAR_SEP}${BIN_DIR}/../../library/tulip-python/tulip-ogl${CHAR_SEP}${BIN_DIR}/../../library/tulip-python/tulipgui${CHAR_SEP}${BIN_DIR}/../../library/tulip-python/stl${CHAR_SEP}$ENV{PYTHONPATH}")
ENDIF(MSVC)
IF(NOT SYSTEM_SIP)
IF(MSVC)
SET(ENV{PYTHONPATH} "${BIN_DIR}/../../thirdparty/sip-4.13.2/siplib/Debug${CHAR_SEP}$ENV{PYTHONPATH}")
ELSE(MSVC)
SET(ENV{PYTHONPATH} "${BIN_DIR}/../../thirdparty/sip-4.13.2/siplib${CHAR_SEP}$ENV{PYTHONPATH}")
ENDIF(MSVC)
ENDIF()
EXECUTE_PROCESS(COMMAND ${SPHINX_EXECUTABLE} -b html -d ${BIN_DIR}/doctrees ${SOURCE_DIR} ${BIN_DIR}/html)
