#!/bin/sh

wd="${0%/*}"
cd "$wd/.."

export DYLD_LIBRARY_PATH="$(pwd)/Frameworks"
export DYLD_FRAMEWORK_PATH="$(pwd)/Frameworks"
export QT_QPA_PLATFORM_PLUGIN_PATH="$(pwd)/PlugIns/platforms"
"$(pwd)"/bin/tulip
