/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c TulipAgentCommunicator -p ../tulip_perspective/include/TulipAgentCommunicator.h:../tulip_perspective/src/TulipAgentCommunicator.cpp resources/org.labri.TulipAgentService.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "TulipAgentCommunicator.h"

/*
 * Implementation of interface class TulipAgentCommunicator
 */

TulipAgentCommunicator::TulipAgentCommunicator(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

TulipAgentCommunicator::~TulipAgentCommunicator()
{
}

